---
title: "Reproducible Research: Peer Assessment 1"
author: "Eric"
date: "March 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading and preprocessing the data


```{r}
data <- read.csv("activity.csv")
str(data)
agg <- aggregate(data$steps, by=list(data$date), FUN=sum, na.rm=TRUE)
hist(agg$x)
````

## What is mean total number of steps taken per day?

````{r}
mean(agg$x)
median(agg$x)
````

## What is the average daily activity pattern?

````{r}
avg <- aggregate(data$steps, by=list(data$interval), FUN=mean, na.rm=TRUE)
plot(avg, type="l")
````


## Imputing missing values

````{r}
dataNNA <- data[!is.na(data$steps),]
dataNA <- data[is.na(data$steps),]
dataNA$steps <- as.factor(dataNA$interval)
levels(dataNA$steps) <- as.numeric(avg$x)
dataNA$steps <- as.integer(as.vector(dataNA$steps))
data2 <- rbind(dataNNA, dataNA)

agg2 <- aggregate(data2$steps, by=list(data2$date), FUN=sum, na.rm=TRUE)

hist(agg2$x)

mean(agg2$x)
median(agg2$x)
````


## Are there differences in activity patterns between weekdays and weekends?

````{r}
library(ggplot2)
data2$wday <- factor(weekdays(as.Date(data2$date)))
data2$dayclass <- factor(ifelse(data2$wday == 'Sunday' | data2$wday == 'Saturday', 'weekend', 'weekday'))

avg2 <- aggregate(data2$steps, by=list(data2$interval, data2$dayclass), FUN=mean, na.rm=TRUE)

names(avg2) = c('interval','dayType','steps')
ggplot(avg2, aes(x = avg2$interval, y = avg2$steps, group = avg2$dayType)) + geom_line() + facet_grid(avg2$dayType ~.) + labs(x = "Interval", y = "Avg Steps", title = "Activity")
````
